Jupyter.local.server.location.string={1}의 {0}
Jupyter.notebook.open.project.processor.name=작업공간 외부에서 파일을 열 때 디렉터리를 연결 안 함
Jupyter.remote.verify.url.empty=Jupyter URL cannot be empty
Jupyter.remote.verify.url.malformed=Malformed URL. Please provide Jupyter URL like http://my.jupyter.org:8888
action.ReloadRemoteFileAction.description=서버에서 최신 변경 내용을 다시 로드합니다
action.ReloadRemoteFileAction.text=서버에서 다시 로드…
group.CellMenu.text=Cell
group.KernelMenu.text=Kernel
notification.group.jupyter=Jupyter notebook