

# Keys are constructed dynamically, see JupyterCellBorderPanel.addButtons()
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"




Jupyter.notebook.open.project.processor.name=작업공간 외부에서 파일을 열 때 디렉터리를 연결하지 마세요
Jupyter.remote.add.connection=Jupyter 연결 추가...
Jupyter.remote.remove.connection.confirmation={0} 연결을 제거하시겠어요?
Jupyter.remote.remove.multiple.files={0} 개의 원격 파일을 삭제할까요?
Jupyter.remote.reconnect=다시 연결…
Jupyter.remote.failed.to.load.remote=원격 파일 로드 중 오류 발생
Jupyter.remote.url=서버 URL:
Jupyter.remote.verify.url.empty=Jupyter URL은 공백일 수 없습니다
Jupyter.remote.verify.url.connection.error=연결 오류
Jupyter.remote.verify.url.malformed=형식이 잘못된 URL입니다. http://my.jupyter.org:8888과 같은 Jupyter URL을 제공하세요
Jupyter.remote.verify.url.not.jupyter=URL에 숨겨진 Jupyter 서버에 도달할 수 없습니다
Jupyter.remote.verify.url.unexpected.error=예기치 않은 오류
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.by.url.text=원격 Jupyter에 연결
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.by.url.connect.button=연결
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.text=원격 Jupyter에 연결
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.description=임시 프로젝트 생성 및 원격 Jupyter 연결

# {0} -- An URL to the server.

# Jupyter settings

Jupyter.remote.add.dialog.title=새 Jupyter 연결
Jupyter.remote.add.dialog.ok.button.text=추가
Jupyter.remote.add.option.discovered.local=실행 중인 로컬 Jupyter 서버에 연결
Jupyter.remote.add.option.managed.local=로컬 Jupyter 서버 시작
Jupyter.remote.add.option.url=URL을 사용하여 Jupyter 서버에 연결
Jupyter.remote.url.discovered.local.combobox=실행 중인 로컬 Jupyter 서버 선택:
Jupyter.remote.url.discovered.no.servers=<서버 없음>
Jupyter.remote.url.managed.local.directory=작업공간 디렉터리:
Jupyter.remote.managed.working.directory.title=Jupyter 작업 디렉터리
Jupyter.remote.verify.managed.empty.path=Jupyter 작업 디렉터리는 공백일 수 없습니다
Jupyter.remote.verify.managed.not.directory=제공된 경로가 디렉터리 경로가 아닙니다
Jupyter.remote.verify.managed.not.absolute=절대 경로여야 합니다
Jupyter.remote.verify.managed.wrong.path=경로에 잘못된 문자가 있습니다
Jupyter.remote.verify.url.wrong.response=Jupyter 연결 오류입니다. 오류 코드: {0}, 메시지: {1}
Jupyter.local.server.location.string={1}의 {0}
Jupyter.remote.verify.url.check.cancelled=확인이 취소되었습니다
Jupyter.remote.verify.url.connecting=Jupyter 연결 확인 중…
action.RefreshRemoteFileAction.text=서버에서 다시 로드…
action.RefreshRemoteFileAction.description=서버에서 최신 변경 내용을 다시 로드합니다
Jupyter.remote.reload.file.from.server.dialog.question={0}의 최신 버전이 서버에 있습니다. 이 버전으로 로컬 사본을 덮어쓰시겠어요?
Jupyter.remote.reload.file.from.server.dialog.title=원격 파일로 로컬 파일을 덮어쓰시겠어요?
Jupyter.remote.reload.file.from.server.dialog.checkbox.remember.my.choice=선택 항목 기억(&R)
Jupyter.remote.reload.file.from.server.all.files.are.up.to.date=모든 파일이 최신 상태입니다
Jupyter.remote.reload.file.from.server.number.of.files.reloaded={0,choice,1#{0} 파일|2#{0}개 파일}이 업데이트되었습니다
Jupyter.remote.refactoring.rename=이름 변경
Jupyter.remote.refactoring.renaming.to=''{0}''의 이름을 다음으로 변경:
Jupyter.remote.refactoring.rename.notebook=Notebook 이름 변경
Jupyter.remote.refactoring.rename.file=파일 이름 변경
Jupyter.remote.refactoring.rename.directory=디렉터리 이름 변경
Jupyter.remote.copying=''{0}''을(를) ''{1}''(으)로 복사 중…
Jupyter.remote.verify.cant.create.path=제공된 경로가 올바르지 않습니다
notification.group.jupyter=Jupyter notebook
Jupyter.remote.unable.to.create.target.dir=타깃 디렉터리 ''{0}''을(를) 생성할 수 없습니다
Jupyter.remote.unknown.remote.file.status.copying.aborted=원격 ''{0}'' 파일이 있는지 확인할 수 없습니다. 복사 프로세스가 중단됩니다.
Jupyter.remote.copying.multiple=여러 파일을 ''{0}''(으)로 복사하는 중…