

# Keys are constructed dynamically, see JupyterCellBorderPanel.addButtons()
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"




Jupyter.notebook.open.project.processor.name=작업 공간 외부에서 파일을 열 때 디렉터리를 연결하지 마세요
Jupyter.remote.add.connection=Jupyter 연결 추가...
Jupyter.remote.pane.title=원격 Jupyter 파일
Jupyter.remote.refresh.selected.node=새로고침
Jupyter.remote.refresh.selected.node.long=원격 Jupyter 파일 트리 새로고침
Jupyter.remote.refresh.all.connections=모든 Jupyter 연결 새로고침
Jupyter.remote.refresh.selected.node.description=원격 Jupyter 서버의 선택된 디렉터리를 재귀적으로 새로고침. 
Jupyter.remote.remove.connection=Jupyter 연결 제거
Jupyter.remote.remove.connection.confirmation={0} 연결을 제거하시겠어요?
Jupyter.remote.remove.multiple.files={0} 개의 원격 파일을 삭제할까요?
Jupyter.remote.reconnect=다시 연결…
Jupyter.remote.select.opened.file=열려 있는 파일 선택
Jupyter.remote.select.opened.file.description=활성화된 에디터에서 열려 있는 파일 선택
Jupyter.remote.tool.window.title=Jupyter 연결
Jupyter.remote.tool.window.no.connections.title=추가된 Jupyter 연결이 없습니다.
Jupyter.remote.failed.to.load.remote=원격 파일 로드 중 오류 발생
Jupyter.remote.url=Jupyter Notebook URL:
Jupyter.remote.verify.url.empty=Jupyter URL은 공백일 수 없습니다
Jupyter.remote.verify.url.connection.error=연결 오류
Jupyter.remote.verify.url.not.jupyter=URL에 숨겨진 Jupyter 서버에 도달할 수 없습니다
Jupyter.remote.verify.url.unexpected.error=예기치 않은 오류
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.by.url.text=원격 Jupyter에 연결
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.by.url.connect.button=연결
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.text=원격 Jupyter에 연결
Jupyter.remote.welcome.screen.connect.to.remote.jupyter.description=임시 프로젝트 생성 및 원격 Jupyter 연결

# {0} -- An URL to the server.

# Jupyter settings

Jupyter.remote.add.dialog.ok.button.text=추가
Jupyter.remote.verify.managed.empty.path=Jupyter 작업 디렉터리는 공백일 수 없습니다
Jupyter.remote.verify.managed.not.directory=제공된 경로가 디렉터리 경로가 아닙니다
Jupyter.remote.verify.managed.not.absolute=절대 경로여야 합니다
Jupyter.remote.verify.managed.wrong.path=경로에 잘못된 문자가 있습니다
Jupyter.remote.verify.url.wrong.response=Jupyter 연결 오류입니다. 오류 코드: {0}, 메시지: {1}
Jupyter.local.server.location.string={1}의 {0}
Jupyter.remote.add.option.managed.local=로컬 Jupyter 서버 시작
Jupyter.remote.add.option.url=URL을 사용하여 Jupyter 서버에 연결
Jupyter.remote.verify.url.check.cancelled=점검이 취소되었습니다
Jupyter.remote.verify.url.connecting=Jupyter 연결 확인 중…
action.RefreshRemoteFileAction.text=서버에서 다시 로드…
action.RefreshRemoteFileAction.description=서버에서 최신 변경사항을 다시 로드합니다
Jupyter.remote.reload.file.from.server.dialog.question={0} 새로운 버전이 서버에 있습니다. 새 버전으로 로컬 사본을 덮어쓰겠습니까?
Jupyter.remote.reload.file.from.server.dialog.title=원격 파일로 로컬 파일을 덮어쓰겠습니까?
Jupyter.remote.reload.file.from.server.dialog.checkbox.remember.my.choice=선택 항목 기억(&R)
Jupyter.remote.reload.file.from.server.all.files.are.up.to.date=모든 파일이 최신 상태입니다
Jupyter.remote.reload.file.from.server.number.of.files.reloaded={0,choice,1#{0} 파일|2#{0}개 파일}이 업데이트되었습니다
Jupyter.remote.refactoring.rename=이름 바꾸기
Jupyter.remote.refactoring.renaming.to=''{0}''의 이름을 다음으로 변경:
Jupyter.remote.refactoring.rename.notebook=노트북 이름 변경
Jupyter.remote.refactoring.rename.file=파일 이름 변경
Jupyter.remote.refactoring.rename.directory=디렉터리 이름 변경